version: '3.7'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 8377
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - app

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./config/.env
    depends_on:
      - db
    networks:
      - app

volumes:
  pgdata:

networks:
  app:
    driver: bridge