version: '3.7'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 8377
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - app

  bot:
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./config/.env
    depends_on:
      - nginx
      - db
    networks:
      - app

  server:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  pgdata:

networks:
  app:
    driver: bridge